# Lauflicht

from machine import Pin
from time import sleep
import random

LAGEa=machine.Pin(18,Pin.OUT,value=1)
LAGEb=machine.Pin(19,Pin.OUT,value=1)
LAGEc=machine.Pin(20,Pin.OUT,value=1)

LEDa=machine.Pin(2,Pin.OUT,value=0)
LEDb=machine.Pin(3,Pin.OUT,value=0)
LEDc=machine.Pin(4,Pin.OUT,value=0)
LEDd=machine.Pin(6,Pin.OUT,value=0)
LEDe=machine.Pin(7,Pin.OUT,value=0)
LEDf=machine.Pin(8,Pin.OUT,value=0)
LEDg=machine.Pin(10,Pin.OUT,value=0)
LEDh=machine.Pin(11,Pin.OUT,value=0)
LEDi=machine.Pin(12,Pin.OUT,value=0)

delay_a = .5
delay_b = .25

def verarbeiten():
    for n in range (2):
        LEDa.value(1)
        LEDb.value(1)
        LEDc.value(1)
        LEDd.value(1)
        LEDe.value(1)
        LEDf.value(1)
        LEDg.value(1)
        LEDh.value(1)
        LEDi.value(1)
        LAGEa.value(0)
        sleep(delay_a)
        LAGEa.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LAGEc.value(0)
        sleep(delay_a)
        LAGEc.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LAGEa.value(0)
        sleep(delay_a)
        LAGEa.value(1)
        LEDa.value(0)
        LEDb.value(0)
        LEDc.value(0)
        LEDd.value(0)
        LEDe.value(0)
        LEDf.value(0)
        LEDg.value(0)
        LEDh.value(0)
        LEDi.value(0)
        
def sortieren_a():
    for n in range (1):
        LEDa.value(1)
        LAGEa.value(0)
        sleep(delay_a)
        LAGEa.value(1)
        LEDa.value(0)
        sleep(delay_b)
        
        LEDb.value(1)
        LEDd.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LEDb.value(0)
        LEDd.value(0)
        sleep(delay_b)
        
        LEDc.value(1)
        LEDe.value(1)
        LEDg.value(1)
        LAGEc.value(0)
        sleep(delay_a)
        LAGEc.value(1)
        LEDc.value(0)
        LEDe.value(0)
        LEDg.value(0)
        sleep(delay_b)
        
        LEDf.value(1)
        LEDh.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LEDf.value(0)
        LEDh.value(0)
        sleep(delay_b)
        
        LEDi.value(1)
        LAGEa.value(0)
        sleep(delay_a)
        LAGEa.value(1)
        LEDi.value(0)
        sleep(delay_b)
        
def sortieren_b():
    for n in range (1):
        LEDg.value(1)
        LAGEc.value(0)
        sleep(delay_a)
        LAGEc.value(1)
        LEDg.value(0)
        sleep(delay_b)
        
        LEDh.value(1)
        LEDd.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LEDh.value(0)
        LEDd.value(0)
        sleep(delay_b)
        
        LEDa.value(1)
        LEDe.value(1)
        LEDi.value(1)
        LAGEa.value(0)
        sleep(delay_a)
        LAGEa.value(1)
        LEDa.value(0)
        LEDe.value(0)
        LEDi.value(0)
        sleep(delay_b)
        
        LEDf.value(1)
        LEDb.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LEDf.value(0)
        LEDb.value(0)
        sleep(delay_b)
        
        LEDc.value(1)
        LAGEc.value(0)
        sleep(delay_a)
        LAGEc.value(1)
        LEDc.value(0)
        sleep(delay_b)

def sortieren_c():
    for n in range (1):
        LEDa.value(1)
        LEDd.value(1)
        LEDg.value(1)
        LAGEa.value(0)
        sleep(delay_a)
        LAGEa.value(1)
        LEDa.value(0)
        LEDd.value(0)
        LEDg.value(0)
        sleep(delay_b)
        
        LEDb.value(1)
        LEDe.value(1)
        LEDh.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LEDb.value(0)
        LEDe.value(0)
        LEDh.value(0)
        sleep(delay_b)
        
        LEDc.value(1)
        LEDf.value(1)
        LEDi.value(1)
        LAGEc.value(0)
        sleep(delay_a)
        LAGEc.value(1)
        LEDc.value(0)
        LEDf.value(0)
        LEDi.value(0)
        sleep(delay_b)
        
        LEDa.value(1)
        LEDd.value(1)
        LEDg.value(1)
        LAGEc.value(0)
        sleep(delay_a)
        LAGEc.value(1)
        LEDa.value(0)
        LEDd.value(0)
        LEDg.value(0)
        sleep(delay_b)
        
        LEDb.value(1)
        LEDe.value(1)
        LEDh.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LEDb.value(0)
        LEDe.value(0)
        LEDh.value(0)
        sleep(delay_b)
        
        LEDc.value(1)
        LEDf.value(1)
        LEDi.value(1)
        LAGEa.value(0)
        sleep(delay_a)
        LAGEa.value(1)
        LEDc.value(0)
        LEDf.value(0)
        LEDi.value(0)
        sleep(delay_b)

def sortieren_d():
    for n in range (1):
        LEDa.value(1)
        LEDb.value(1)
        LEDc.value(1)
        LAGEa.value(0)
        sleep(delay_a)
        LAGEa.value(1)
        LEDa.value(0)
        LEDb.value(0)
        LEDc.value(0)
        sleep(delay_b)
        
        LEDd.value(1)
        LEDe.value(1)
        LEDf.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LEDd.value(0)
        LEDe.value(0)
        LEDf.value(0)
        sleep(delay_b)
        
        LEDg.value(1)
        LEDh.value(1)
        LEDi.value(1)
        LAGEc.value(0)
        sleep(delay_a)
        LAGEc.value(1)
        LEDg.value(0)
        LEDh.value(0)
        LEDi.value(0)
        sleep(delay_b)
        
        LEDa.value(1)
        LEDb.value(1)
        LEDc.value(1)
        LAGEc.value(0)
        sleep(delay_a)
        LAGEc.value(1)
        LEDa.value(0)
        LEDb.value(0)
        LEDc.value(0)
        sleep(delay_b)
        
        LEDd.value(1)
        LEDe.value(1)
        LEDf.value(1)
        LAGEb.value(0)
        sleep(delay_a)
        LAGEb.value(1)
        LEDd.value(0)
        LEDe.value(0)
        LEDf.value(0)
        sleep(delay_b)
        
        LEDg.value(1)
        LEDh.value(1)
        LEDi.value(1)
        LAGEa.value(0)
        sleep(delay_a)
        LAGEa.value(1)
        LEDg.value(0)
        LEDh.value(0)
        LEDi.value(0)
        sleep(delay_b)
        
def denken():
    random.seed
    z=random.randint (20,200)
    print (z)
    for n in range (z):
        random.seed
        LED_einzel = (LEDa,LEDb,LEDc,LEDd,LEDe,LEDf,LEDg,LEDh,LEDi)
        led = random.choice(LED_einzel )
        random.seed
        LAGE_einzel = (LAGEa,LAGEb,LAGEc)
        lage = random.choice(LAGE_einzel)
    
        lage.value(0)
        led.value(1)
        sleep(delay_b)
        led.value(0)
        lage.value(1)
    
while True:
    denken()
    sortieren_a()
    sortieren_b()
    sortieren_c()
    sortieren_d()
    verarbeiten()